# Generated by Django 4.2.7 on 2024-02-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('scan_id', models.CharField(max_length=255)),
                ('scan_result', models.JSONField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'URL_scan_custom_user',
            },
        ),
        migrations.AlterModelTable(
            name='filescan',
            table='file_scan_custom_user',
        ),
    ]
